spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tumo?useSSL=false
    username: root
    password: 1234

tumo:
  jwt:
    # 密钥
    admin-secret-Key: itmoli
    # 时长
    admin-ttl: 7200000
      # 令牌名称
    admin-token-name: token

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #是否开启下划线和驼峰的映射
    cache-enabled: false #是开启二级缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      update-strategy: not_null #更新策略：只更新非空字段

logging:
  level:
    sql: debug

